server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chx?usessl=flase&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 1
      pool-name: Hikari_CP
      idle-timeout: 60000
      max-lifetime: 60000
      connection-timeout: 60000
#  rabbitmq:
#    host: 127.0.0.1
#    username: guest
#    password: guest
#    virtual-host: /
#    port: 5672
#    publisher-confirm-type: correlated #确认机制，不配的话收不到setConfirmCallback
logging:
  level:
    root: debug